---
#
# Ansible managed
#

name: "Dependabot Merge"

on:
  pull_request:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot_merge:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: Auto Merge Dependabot Updates
        uses: "buluma/gh-action-auto-merge-dependabot-updates@master"
        with:
          allowed-actors: dependabot-preview[bot], dependabot[bot]
